version: '3'

services:
  urb_home_guard_backend:
    build:
      context: backend
      dockerfile: './Dockerfile'
    ports:
      - '5000:5000'
    environment:
      FLASK_DEBUG: 1
    restart: always
    volumes: ['./:/src'] # reload changes automatically