version: '3'

services:
  urb_home_guard_backend:
    build:
      context: backend
      dockerfile: './Dockerfile'
    depends_on:
      s3:
        condition: service_healthy
    ports:
      - '5000:5000'
    environment:
      FLASK_DEBUG: 1
    restart: always
    volumes: ['./:/src'] # reload changes automatically

  s3:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z # TODO: update to newer version
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 5