name: Run backend functional tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/compose-cli@v1
      with:
        compose-version: 3.x

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up temp environment
      run: make start-env

    - name: Run functional tests
      run: make test-functional